name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
      
      - name: Authenticate to Prod Org
        run: |
          sf org login web --client-id 3MVG97L7PWbPq6UzT7YBOMxUNgKYQM.UQHHhsDlX.wK8AOnj0PrqRZqrA0Qt7g0CHrFSFMToN9vSEgsM_nlAp \
            --client-secret 26938DECCB3B73433D227BD4E6BB44CEBDFBAE225732E04CFBF83A970FF21835 \
            --refresh-token ${{ secrets.SF_REFRESH_TOKEN }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --username ${{ secrets.SF_USERNAME }} \
            --alias ProdOrg

            
      - name: Deploy to Prod
        run: |
          sf project deploy start --target-org ProdOrg --source-dir force-app
