name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
      
      - name: Authenticate to Prod Org
        run: |
          sf org login access-token --instance-url https://orgfarm-a3747e72e3-dev-ed.develop.my.salesforce.com \
            --access-token 5Aep8618MtpGySpPxj6LWUeF_ypWht8yJB0drnqHGoA_buiDn0LI_nGpoby1zhJJpFBvs0WVu33C8G7BofCsrDy \
            --alias ProdOrg

      - name: Deploy to Prod
        run: |
          sf project deploy start --target-org ProdOrg --source-dir force-app
