name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
      
      - name: Authenticate to Prod Org
        run: |
          sf org login web --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --client-secret ${{ secrets.SF_CONSUMER_SECRET }} \
            --refresh-token ${{ secrets.SF_REFRESH_TOKEN }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --username ${{ secrets.SF_USERNAME }} \
            --alias ProdOrg
            
      - name: Deploy to Prod
        run: |
          sf project deploy start --target-org ProdOrg --source-dir force-app
